docs: move accessibility document over
seedcase-project/design pull request #119
Opened 2024-06-28 11:40 UTC by K-Beicher

## Description

- This PR moves the accessibility why document over to design, and re-words a bit of it.
- These changes are done because the topic fits better under its own heading in design and not as a traditional why decision post.

## Related Issues

Closes #89 

## Reviewer Focus

This PR only needs a quick review.

Mostly the same text as before, but the hidden sections have been removed.

## Checklist

For general documentation:

- [x] Spell-check
    - [ ] US
    - [ ] UK
- [ ] Did the page(s) preview correctly on your machine without breaking
- [ ] New category words (keywords) (if any) added to the code snippet file

2024-06-28 12:46 UTC, signekb requested changes
Very nice! I have some suggestions now that it's not a traditional decision post anymore

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +both the websites, the software products, and the teaching material.
```suggestion
speakers, and people who are not familiar with technology.
```
There seems to be some duplicated text here

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +
```suggestion
```
This header seems to be a leftover from when this was a decision post. The next section could fit under the Introduction header above.

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +## Considered options
```suggestion
```
Same with this header

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +### Accessible content
```suggestion
## Accessible content
```
Then this header can be level 2 instead

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +### Visual accessibility
```suggestion
## Visual accessibility
```

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +the hidden text. Ensuring that the language isn't too technical or
```suggestion
everyone. This includes things like accessible naming and using a polite
setting for hidden text. Ensuring that the language isn't too technical or
```

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +complex, and that pictures and potential audio/visual content is
```suggestion
complex, and that pictures and potential audio/visual content are
```

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +    reader in a logical way?
```suggestion
    reader in a logical way? (i.e., do we avoid skipping header levels?)
```
or something like this?

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +-   are the interactive states easy to see (default, focus/hover,
```suggestion
-   are the interactive states of buttons easy to see (default, focus/hover,
```
Or do these states include other elements than buttons?

2024-06-28 12:46 UTC, signekb commented on accessibility/index.qmd
> +## Decision outcome
```suggestion
## Conclusion
```
Or at least something different than "Decision outcome"? :)

2024-06-28 12:57 UTC, signekb submitted a review, later dismissed

2024-07-07 21:37 UTC, lwjohnst86 requested changes

2024-07-07 21:37 UTC, lwjohnst86 approved these changes

2024-07-07 21:38 UTC, merged